### PR TITLE
Create player.sl.yml

### PR DESCRIPTION
**Pull request by oscarvideodesk**
Creation of slovenian translation file for FO module

### CODE REVIEW

**Comment by gasp** [comment]
@oscarvideodesk is this the only file needed to be created ? nothing concerning BO ?

**Comment by oscarvideodesk** [comment]
Agents shall work in english only. The needed translation by now is only on the visible webuser's part, that is, the standard module's messages only

**Comment by gasp** [comment]
great ! 👍 
thanks you for your contribution :-)

**Comment by oscarvideodesk** [comment]
Always a pleasure working with you ! ;)

**Pull request merged**
