### PR TITLE
Update player.jp.yml

### PR DESCRIPTION
**Pull request by HironoriSong**
fo_176 We would like to have this window for each customer on Back office. This comment appear at email title of conversation log.  Each customer receive our conversations log from each companies. So, it is better for our customer to change this message by themselves.

### CODE REVIEW

**Comment by oscarvideodesk** [comment]
Dear Videodesk R&D team. Please comit this pull request. The goal is to remove "softbank" reference in the japanese translation so the result is more generic for japanese customers.

**Comment by gasp** [comment]
Are there other references to "Softbank" into the translation files ?

**Comment by HironoriSong** [comment]
I don't see it on here. However, I'm not sure about the other place.
https://github.com/videodesk/TranslationModule/blob/master/Resources/translations/player.jp.yml

**Comment by gasp** [comment]
Looks clean, agreed to merge ! 👌 
thank you for your contribution @HironoriSong and for your reactivity @oscarvideodesk !

**Pull request merged**
