### PR TITLE
Japanese Updating

### PR DESCRIPTION
**Pull request by HironoriSong**
We would like to adjust fo_59,107,162,an 208. Please check and accept it. 

Thank you,
Nori

### CODE REVIEW

**Comment by sergesah** [comment]
Hello Nori

could you explicit whether this is for the asiaenv1 environment Sumishin or
for the regular my.videodesk.com environment?

Regis Duval

**Comment by HironoriSong** [comment]
Hello Regis,

This is the change what we need it on asiaenv1.videodesk.com. Does it work
on perfectly different one , compared with my.videodesk.com's one?

Nori

---
*＜videodesk / Web接客ツール（ビデオチャット）＞*
*http://www.softbank.jp/biz/other/videodesk/
<http://www.softbank.jp/biz/other/videodesk/>*
---
宋 浩典 Hironori SONG
ソフトバンク株式会社 SoftBank Corp.
法人事業開発本部   Enterprise Business Development Unit
事業開発第三統括部 Business Development 3rd Unit.
+81-80-4296-7924 hironori.soh@g.softbank.co.jp

2017-09-15 19:34 GMT+09:00 sergesah <notifications@github.com>:

**Comment by HironoriSong** [comment]
Hello Nori

no, it is the same process, but different databases

Regis Duval

**Comment by HironoriSong** [comment]
Hello Regis,

We got it.

Thank you,
Nori

Nori SONG +81-80-4296-7924
hironori.soh@g.softbank.co.jp
Sent from my iPhone ⌘

On Sep 15, 2017, at 22:33, Régis Duval <regis@videodesk.com> wrote:

Hello Nori

no, it is the same process, but different databases

Regis Duval

**Pull request merged**
